openapi: 3.0.3
info:
  title: rideRota API
  version: 1.0.0
tags:
  - name: Authentication
    description: Operations for user authentication and session management.
  - name: User Management
    description: Operations for creating different types of users.

paths:
  /api/auth/signup/superadmin:
    post:
      summary: Superadmin and Tenant Signup
      tags: [Authentication & Onboarding]
      description: >
        Creates a new superadmin user and their associated tenant.
        On success, returns access and refresh tokens via HttpOnly Set-Cookie headers.
      requestBody:
        description: Superadmin and new tenant details.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SuperadminCreatePayload"
      responses:
        "201":
          description: >
            User and tenant created successfully.
            Tokens are returned in HttpOnly cookies.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericSuccessResponse"
        "400":
          description: Bad Request / Validation Error
        "409":
          description: Conflict - A user or tenant with these details already exists.

  /api/auth/signup/admin:
    post:
      summary: Admin Signup
      tags: [Authentication & Onboarding]
      description: >
        Creates a new admin user.
        On success, returns access and refresh tokens via HttpOnly Set-Cookie headers.
      requestBody:
        description: Admin user details.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AdminCreatePayload"
      responses:
        "201":
          description: >
            User created successfully.
            Tokens are returned in HttpOnly cookies.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "accessToken=...; HttpOnly; Secure; Path=/; Max-Age=900"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericSuccessResponse"
        "400":
          description: Bad Request / Validation Error
        "409":
          description: Conflict - A user with these details already exists.

  /api/auth/signup/driver:
    post:
      summary: Driver Signup
      tags: [Authentication & Onboarding]
      description: >
        Creates a new driver user.
        On success, returns access and refresh tokens via HttpOnly Set-Cookie headers.
      requestBody:
        description: Driver user details.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DriverCreatePayload"
      responses:
        "201":
          description: >
            User created successfully.
            Tokens are returned in HttpOnly cookies.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "accessToken=...; HttpOnly; Secure; Path=/; Max-Age=900"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericSuccessResponse"
        "400":
          description: Bad Request / Validation Error
        "409":
          description: Conflict - A user with these details already exists.

  /api/auth/signup/employee:
    post:
      summary: Employee Signup
      tags: [Authentication & Onboarding]
      description: >
        Creates a new employee user.
        On success, returns access and refresh tokens via HttpOnly Set-Cookie headers.
      requestBody:
        description: Employee user details.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EmployeeCreatePayload"
      responses:
        "201":
          description: >
            User created successfully.
            Tokens are returned in HttpOnly cookies.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "accessToken=...; HttpOnly; Secure; Path=/; Max-Age=900"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GenericSuccessResponse"
        "400":
          description: Bad Request / Validation Error
        "409":
          description: Conflict - A user with these details already exists.

  /api/auth/whoami:
    get:
      summary: Get Current User Details
      tags: [Authentication]
      description: >
        Retrieves the details of the currently authenticated user based on the session
        token provided in the request cookies.
      responses:
        "200":
          description: User details retrieved successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AdministrationDetails"
        "401":
          description: Unauthorized - The user is not authenticated or the session has expired.
  # You would have a similar login endpoint
  /api/auth/login/administration:
    post:
      summary: User Login
      tags: [Authentication & Onboarding]
      description: >
        Authenticates a user. On success, returns access and refresh
        tokens via HttpOnly Set-Cookie headers.
      requestBody:
        description: User credentials for login
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginPayload"
      responses:
        "200":
          description: Login successful. Tokens are returned in HttpOnly cookies.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDetails"
        "401":
          description: Unauthorized - Invalid email or password.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid email or password."

  /api/invite:
    post:
      summary: Invite a new User
      tags: [User Management]
      requestBody:
        description: User email and type
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserInvitePayload"
      responses:
        "201":
          $ref: "#/components/schemas/GenericSuccessResponse"
        "400":
          description: Bad Request / Validation Error

  /api/auth/clearSession:
    post:
      summary: Clear User Session
      tags: [Authentication]
      description: >
        Logs the user out by clearing the access and refresh token cookies.
      responses:
        "200":
          description: >
            Session cleared successfully. The authentication cookies have been invalidated.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: "accessToken=; HttpOnly; Secure; Path=/; Max-Age=0"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Session cleared successfully."
        "500":
          description: >
            An error occurred while clearing the session.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Failed to clear session."

  /api/tenant/create:
    post:
      tags:
        - Tenant Management
      summary: Create a new tenant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TenantCreatePayload"
      responses:
        "201":
          description: Tenant created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TenantDetails"
        "400":
          description: Bad request, validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid input data"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An unexpected error occurred."

  /api/tenant/slug/check-if-exists:
    get:
      summary: Check if a tenant slug exists
      tags: [Tenant Management]
      parameters:
        - in: query
          name: slug
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Endpoint ran successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  exists:
                    type: boolean
                    example: true
        "404":
          description: Error checking for slug
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error checking for slug."

components:
  schemas:
    UserInvitePayload:
      type: object
      properties:
        userType:
          type: string
          enum: [admin, driver, employee]
          description: "The type of user to invite."
          example: "admin"
        email:
          type: string
          format: email
          example: "admin@example.com"
      required:
        - email

    # --- Base Types ---
    UserBase:
      type: object
      properties:
        name:
          type: string
          example: "John Doe"
        age:
          type: integer
          example: 30
        phoneNo:
          type: string
          example: "+11234567890"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        profileImgUrl:
          type: string
          format: uri
          nullable: true
          example: "https://example.com/profile.jpg"
      required:
        - name
        - phoneNo
        - email

    UserCreatePayload:
      allOf:
        - $ref: "#/components/schemas/UserBase"
        - type: object
          properties:
            password:
              type: string
              description: "The user's regular password."
              example: "$2b$10$K2.09uI5GU.J4sF2uB5gIuJ0Z5jJ6X3Y2Z5jJ6X3Y2Z5jJ6X3Y2Z"
          required:
            - password

    LoginPayload:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required:
        - email
        - password

    ApiResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    # --- User Payloads & Responses ---
    SuperadminCreatePayload:
      allOf:
        - $ref: "#/components/schemas/UserCreatePayload"

    AdminCreatePayload:
      allOf:
        - $ref: "#/components/schemas/UserCreatePayload"

    EmployeeCreatePayload:
      allOf:
        - $ref: "#/components/schemas/UserCreatePayload"
        - type: object
          properties:
            location:
              type: string
              description: "The employee's home address or pickup location."
              example: "123 Main St, Anytown, USA"
          required:
            - location

    DriverCreatePayload:
      allOf:
        - $ref: "#/components/schemas/UserCreatePayload"
        - type: object
          properties:
            carMake:
              type: string
              example: "Toyota"
            carName:
              type: string
              example: "Camry"
            carColor:
              type: string
              example: "Blue"
            carPlate:
              type: string
              example: "RIDE-123"
            numberOfSeats:
              type: integer
              example: 4
            carDescription:
              type: string
              nullable: true
          required:
            - carMake
            - carName
            - carColor
            - carPlate
            - numberOfSeats

    UserDetails:
      type: object
      description: "Public details of a user."
      properties:
        id:
          type: string
          description: "The user's unique identifier."
          example: "clxjq1z0a0000e8b4c2g7h6k9"
        email:
          type: string
          format: email
          example: "john.doe@example.com"
        name:
          type: string
          example: "John Doe"
        age:
          type: integer
          nullable: true
          example: 30
        phoneNo:
          type: string
          example: "+11234567890"
        profileImgUrl:
          type: string
          format: uri
          nullable: true
          example: "https://example.com/profile.jpg"
        role:
          type: string
          enum: [SUPERADMIN, ADMIN, DRIVER, EMPLOYEE]
          example: "EMPLOYEE"
        status:
          type: string
          enum: [PENDING, MEMBER]
          example: "ACTIVE"
        tenantSlug:
          type: string
          nullable: true
          description: "The slug of the tenant the user belongs to."
          example: "innovate-inc"

    GenericSuccessResponse:
      type: object
      properties:
        message:
          type: string
          example: "Authentication successful."

    TenantCreatePayload:
      type: object
      properties:
        name:
          type: string
          description: "The name of the new tenant."
          example: "Innovate Inc."
        slug:
          type: string
          description: "A unique identifier for the tenant."
          example: "innovate-inc"
        office_name:
          type: string
          description: "The name of the office associated with the tenant."
          example: "Innovate HQ"
        office_location:
          type: string
          description: "The location of the office associated with the tenant."
          example: "123 Innovation Drive, Tech City"
      required:
        - name
        - office_name
        - office_location
        - slug

    TenantDetails:
      allOf:
        - $ref: "#/components/schemas/TenantCreatePayload"
        - type: object
          properties:
            id:
              type: string
              description: "The unique identifier for the tenant."
              example: "tenant_123"
            createdAt:
              type: string
              format: date-time
              description: "The date and time when the tenant was created."
              example: "2023-01-01T12:00:00Z"
            superAdminId:
              type: string
              description: "The unique identifier for the super admin user."
              example: "user_456"

    AdministrationDetails:
      type: object
      description: "Public details of a user involved in the administration"
      properties:
        userDetails:
          $ref: "#/components/schemas/UserDetails"
        tenantDetails:
          $ref: "#/components/schemas/TenantDetails"

  responses:
    AuthSuccessResponse:
      description: |-
        Request successful. An httpOnly cookie containing an access token and another httpOnly cookie containing a refresh token have been set.
      headers:
        Set-Cookie:
          schema:
            type: string
            example: "accessToken=...; HttpOnly; Path=/; SameSite=Strict"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ApiResponse"
            example:
              message: "Authentication successful"
